

import type { Metadata } from 'next'
import { GlobalDataProvider } from './Context/store'

import './globals.css'



export const metadata: Metadata = {
  title: 'Amazon.in',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <GlobalDataProvider>{children}</GlobalDataProvider></body>
    </html>
  )
}
